package matcher

// PoolChoices is the embedded catalog of known swimming pool options in the EGYM Typeform.
var PoolChoices = []string{
	"ABC Nesselwang",
	"Adolf-Ehrmann-Bad Neureut Karlsruhe",
	"Agrippabad Köln",
	"Alb-Lauchert-Schwimmhalle - Gammertingen",
	"Allwetterbad Flingern (Freibad) Düsseldorf",
	"Allwetterbad Flingern (Hallenbad) Düsseldorf",
	"Alte Badeanstalt Essen",
	"Altes Stadtbad Augsburg",
	"Amalienbad Wien",
	"Aquacity St. Pölten",
	"Aquamathe Iserlohn",
	"aquaplex Eisenach",
	"aquariUSH Unterschleißheim",
	"Aquella Freizeitbad Ansbach",
	"Asbach-Bad Rüdesheim am Rhein",
	"Atlantis Freizeitbad Herzogenaurach",
	"Auebad Kassel",
	"Augartenbad Graz",
	"Auster Freibad Graz",
	"Auster Sportbad Graz",
	"Bad am Berg Kösching",
	"Bad am Stadion Edewecht",
	"Bad Ragnitz Graz",
	"Bad Ransberg Viersen",
	"Bad Straßgang Graz",
	"Bad und Sport Oststadt Essen",
	"Bad zur Sonne Graz",
	"Badehaus Benrath Düsseldorf",
	"Bädergesellschaft Ahlen (Freibad)",
	"Bädergesellschaft Ahlen (Parkbad)",
	"Badesee Coswig-Kötitz",
	"Badesee Liefering Salzburg",
	"Badestelle Weißig Dresden",
	"Badewelt Ishara Bielefeld",
	"Badewelt Köthen",
	"Badschnass Freibad Schramberg",
	"Badschnass Schramberg",
	"Ballhaus Schwimmhalle Aschersleben",
	"Brandlbad | Freibad Neuburg",
	"Brigittenauer Bad Wien",
	"Bültenfreibad Epe Gronau",
	"Carl-Miller-Bad Magdeburg",
	"Chorweilerbad Köln",
	"Citysplash St. Pölten",
	"Das Bad an den Kaiserthermen Trier",
	"Das Nordbad an der Mosel Trier",
	"das Stadtwerk Westbad Regensburg",
	"das Stadtwerk Wöhrdbad Regensburg",
	"Das SüdBad an den Weihern Trier",
	"Döblinger Bad Wien",
	"Donaubad Sigmaringen (Freibad)",
	"Donaustädter Bad Wien",
	"Dünenbad Dörpen",
	"Echazbad - Hallenbad Pfullingen",
	"Elbe-Schwimmhalle Magdeburg",
	"Erich-Rademacher-Freibad Magdeburg",
	"Erlebnisbad Centrelax Berndorf",
	"Erlebnisbad Elbamare Dresden",
	"Erlebnisbad Saaleperle Bernburg",
	"Erlebnisbad Talsperre Malter Dippoldiswalde",
	"Erlebnisoase Schörgenhub Linz",
	"Europabad Karlsruhe",
	"Europabad Wetzlar",
	"Eyachbad Balingen",
	"Fächerbad Karlsruhe",
	"Familienbad Heepen Bielefeld",
	"Familienbad Niederheid Düsseldorf",
	"Familienbad PiORAMA Penzberg",
	"Familienoase Biesenfeld Linz",
	"Fitnessbad Walsrode",
	"Fitnessoase Parkbad Linz",
	"Flavia-Bad Lambach",
	"Floridsdorfer Bad Wien",
	"Frei- und Hallenbad Harsewinkel",
	"Frei- und Hallenbad Reken",
	"Freibad Alpenstraße AYA Bad Salzburg",
	"Freibad am CaLevornia Leverkusen",
	"Freibad Bad Köstritz",
	"Freibad Bärenkeller Bad Augsburg",
	"Freibad Beckum",
	"Freibad Bippen",
	"Freibad Bokeloh Wunstorf",
	"Freibad Borssum Emden",
	"Freibad Brambauer Lünen",
	"Freibad Braunau",
	"Freibad Brentanobad Frankfurt am Main",
	"Freibad Cappenberger See Lünen",
	"Freibad Carl-Benz-Bad Mannheim",
	"Freibad Cotta Dresden",
	"Freibad Dellwig Essen",
	"Freibad Denkendorf",
	"Freibad Dornberg Bielefeld",
	"Freibad Elverdissen Herford",
	"Freibad Eschersheim Frankfurt am Main",
	"Freibad Familienbad am Plärrer Augsburg",
	"Freibad Fischerteich in Pivitsheide Detmold",
	"Freibad Fockbek",
	"Freibad Fribbe Augsburg",
	"Freibad Gadderbaum Bielefeld",
	"Freibad Groß-Gerau",
	"Freibad Gescher",
	"Freibad Harleshausen Kassel",
	"Freibad Hausen Frankfurt am Main",
	"Freibad Herzogenaurach",
	"Freibad Herzogenried Mannheim",
	"Freibad Hiddesen Detmold",
	"Freibad Hillegossen Bielefeld",
	"Freibad im Kleinen Felde Herford",
	"Freibad im peb Passau",
	"Freibad Ingolstadt",
	"Freibad Krumbach",
	"Freibad Kuchen",
	"Freibad Lauterstein",
	"Freibad Lechhausen Augsburg",
	"Freibad Leopoldskron Salzburg",
	"Freibad Lorettobad Freiburg",
	"Freibad Mainburg",
	"Freibad Münsingen",
	"Freibad Mollbeck",
	"Freibad Neubeckum",
	"Freibad Neuenkirchen Melle",
	"Freibad Nieder-Eschbach Frankfurt am Main",
	"Freibad Oldendorf Melle",
	"Freibad Pleinting",
	"Freibad Riemsloh Melle",
	"Freibad Rietberg",
	"Freibad Rolandsbad Paderborn",
	"Freibad Rüppurr Karlsruhe",
	"Freibad Sandhofen",
	"Freibad Sankt Augustin",
	"Freibad Satteldorf",
	"Freibad Schröttinghausen Bielefeld",
	"Freibad Schwarzach",
	"Freibad Schwarzach",
	"Freibad Schwarzenbrink in Heidenoldendorf Detmold",
	"Freibad Silobad Frankfurt am Main",
	"Freibad St. Georgen Freiburg",
	"Freibad Stadion Frankfurt am Main",
	"Freibad Steele Essen",
	"Freibad Strandbad Freiburg",
	"Freibad Süd Magdeburg",
	"Freibad Tostedt",
	"Freibad Vilshofen",
	"Freibad Volksgarten Salzburg",
	"Freibad Waldbad Schloss Neuhaus Paderborn",
	"Freibad Weida",
	"Freibad Weilheim a d Teck",
	"Freibad Wellingholzhausen Melle",
	"Freibad Wilhelmshöhe Kassel",
	"Freibad Wostra Dresden",
	"Freibadverein Berlebeck-Heiligenkirchen Detmold",
	"Freizeitbad (Frei- und Hallenbad) Pfalzgrafenweiler",
	"Freizeitbad Aqua Marien",
	"Freizeitbad CaLevornia Leverkusen",
	"Freizeitbad Düsselstrand Düsseldorf",
	"Freizeitbad Jurawell",
	"Freizeitbad Pullach im Isartal",
	"Freizeitbad Remagen",
	"Freizeitbad Woliday Bitterfeld-Wolfen",
	"Freizeitpark Vöcklabruck Hallenbad",
	"Freizeitpark Vöcklabruck Parkbad",
	"Friedrichsbad Frohnhausen Essen",
	"Friesentherme Emden",
	"Gartenhallenbad Neckarau Mannheim",
	"Gartenhallenbad Unterrath Düsseldorf",
	"Genovevabad Köln",
	"Georg-Arnhold-Bad Dresden (Freibad)",
	"Georg-Arnhold-Bad Dresden (Hallenbad)",
	"Großfeldsiedlungsbad Wien",
	"Grönegaubad Melle",
	"Grugabad Essen",
	"Gumbala Bade- und Saunaland Gummersbach",
	"H2Oh! Tönisvorst",
	"Hadersdorf-Weidlingauer Bad Wien",
	"Hallen- und Freibad Rheinbad Düsseldorf",
	"Hallen- und Freibad Wiembachtal Leverkusen",
	"Hallen-Freibad Hechingen",
	"Hallenbad Alisobad Paderborn",
	"Hallenbad Alpenstraße AYA Bad Salzburg",
	"Hallenbad Altbach",
	"Hallenbad Attendorn",
	"Hallenbad Bad Fallingbostel",
	"Hallenbad Bad Saulgau",
	"Hallenbad Beckum",
	"Hallenbad Boy/Welheim Bottrop",
	"Hallenbad Braunau",
	"Hallenbad Brilon",
	"Hallenbad Derschlag Gummersbach",
	"Hallenbad Dornstadt",
	"Hallenbad Ebingen Albstadt",
	"Hallenbad Faulerbad Freiburg",
	"Hallenbad Fürth Scherbsgraben",
	"Hallenbad Fürth Stadeln",
	"Hallenbad Göggingen Augsburg",
	"Hallenbad Gronau",
	"Hallenbad Groß-Gerau",
	"Hallenbad Grötzingen Karlsruhe",
	"Hallenbad Haslach Freiburg",
	"Hallenbad Haunstetten Augsburg",
	"Hallenbad Herschelbad Mannheim",
	"Hallenbad Hiltrup",
	"Hallenbad Hochdorf Freiburg",
	"Hallenbad Höchst Frankfurt am Main",
	"Hallenbad Hombruch Dortmund",
	"Hallenbad im peb Passau",
	"Hallenbad im Sportpark Bottrop",
	"Hallenbad im Sportpark Bottrop",
	"Hallenbad Kinderhaus Münster",
	"Hallenbad Kirchhellen Bottrop",
	"Hallenbad Langenwand Albstadt",
	"Hallenbad Liblar Erfstadt",
	"Hallenbad Lehen Freiburg",
	"Hallenbad Mannheim Vogelstang",
	"Hallenbad Maulburg",
	"Hallenbad Menden Sankt Augustin",
	"Hallenbad Mitte Münster",
	"Hallenbad Mössingen",
	"Hallenbad Mühldorf am Inn",
	"Hallenbad Münsingen",
	"Hallenbad Nord Tübingen",
	"Hallenbad Nörten-Hardenberg",
	"Hallenbad Oelde",
	"Hallenbad Onstmettingen Albstadt",
	"Hallenbad Ravensburg",
	"Hallenbad Recklinghausen",
	"Hallenbad Residenzbad Schloss Neuhaus Paderborn",
	"Hallenbad Riedlingen",
	"Hallenbad Schwechat",
	"Hallenbad Süd Kassel",
	"Hallenbad Südwest Ingolstadt",
	"Hallenbad Süßen",
	"Hallenbad TollKün Künzelsau",
	"Hallenbad Unterhausen",
	"Hallenbad Villingen",
	"Hallenbad Vilsbiburg",
	"Hallenbad Vilshofen",
	"Hallenbad Waldhof-Ost",
	"Hallenbad Westbad Freiburg",
	"Hallenschwimmbad Georgensmünd",
	"Harske Badehuus Haren (Ems)",
	"Hietzinger Bad Wien",
	"Hummetalbäder Aerzen",
	"Höhenbergbad Köln",
	"Hohenlohe Ausee Enns",
	"Höpflerbad Wien",
	"Hüttelsdorfer Bad Wien",
	"Jörgerbad Wien",
	"Karlsbad Halle (Saale)",
	"Kneippbad Villingen-Schwenningen",
	"Kombibad Prohlis Dresden",
	"Kongreßbad Wien",
	"Krapfenwaldlbad Wien",
	"Laaerbergbad Wien",
	"Lentpark Hallenbad Köln",
	"Liesinger Bad Wien",
	"Lieth-Freibad Bad Fallingbostel",
	"Lippe Bad Lünen",
	"Luftbad Dölzschen Dresden",
	"Main Bad Bornheim Frankfurt",
	"Margaretenbad Graz",
	"Mineralfreibad Mainhardt",
	"Münster Therme Düsseldorf",
	"Naherholungszentrum Barleber See Magdeburg",
	"Naherholungszentrum Neustädter See Magdeburg",
	"Naturbad Brackwede Bielefeld",
	"Naturfreibad Eichmühle Bad Tölz",
	"Naturbad Kaimberg Gera",
	"Naturbad Mockritz Dresden",
	"Naturbad Münchenbernsdorf",
	"Naturbad Winsen",
	"Naturbadestelle Silbersee Haltern am See",
	"Naturerlebnisbad Uetze",
	"Naturgartenbad Nürnberg",
	"Naturfreibad Bruch Gummersbach",
	"Naturfreibad Haunstetten Augsburg",
	"Naturfreibad Suderwich",
	"Naturfreibad Vingst Köln",
	"Neckarbad Schwenningen",
	"Neisse-Bad Görlitz",
	"Neptun-Schwimmhalle Rostock",
	"Nord-Ost-Bad Schonnebeck Essen",
	"Nordbad Dortmund",
	"Nordbad Halle",
	"Ohase - Das Freibad Bersenbrück",
	"Ohase - Das Hallenbad Ankum",
	"Ökobad Lindenthal Leipzig",
	"Ossendorfbad Köln",
	"Ottakringer Bad Wien",
	"Panoramabad Farchant",
	"Panorama-Bad Freudenstadt",
	"Panorama-Freibad Freudenstadt",
	"Panoramabad Georgsmarienhütte",
	"Paracelsus Bad Salzburg",
	"Parkbad | Hallenbad Neuburg",
	"Parkfreibad Gronau",
	"Parkschwimmbad Rheinau",
	"PartheBad Taucha",
	"Pinneberger Bäder Pinneberg",
	"Rheinblick 741 Düsseldorf",
	"Rheingaubad Geisenheim",
	"Rheinstrandbad Rappenwört Karlsruhe",
	"Riedbad Bergen-Enkheim",
	"Robert-Koch-Schwimmhalle Halle",
	"Rodenkirchenbad Köln",
	"RothenburgBad Rothenburg ob der Tauber",
	"Röhrscheidtbad Gesundbrunnen Bautzen",
	"Römer Therme Dormagen",
	"Saline Bad Halle",
	"Schafbergbad Wien",
	"Schlossbad Bruck",
	"Schlossbad Grevenbroich",
	"Schlossbad Niederrhein Mönchengladbach",
	"Schönbergbad - Freibad Pfullingen",
	"Schreberbad Leipzig",
	"Schwarzlsee Graz",
	"Schwimm' in Bilk Düsseldorf",
	"Schwimmbad Bad Tölz",
	"Schwimmbad Grünauer Welle Leipzig",
	"Schwimmbad Schwarzach",
	"Schwimmbad Sportpark Ost Regensburg",
	"Schwimmbad Werfen",
	"Schwimmbad Werneck",
	"Schwimmhalle Bühlau Dresden",
	"Schwimmhalle Große Diesdorfer Straße Magdeburg",
	"Schwimmhalle Hannes Präkel Bergen auf Rügen",
	"Schwimmhalle Klotzsche Dresden",
	"Schwimmhalle Mitte Leipzig",
	"Schwimmhalle Neustadt Halle",
	"Schwimmbad Nienburg",
	"Schwimmhalle Nord Leipzig",
	"Schwimmhalle Nord Magdeburg",
	"Schwimmhalle Nordost Leipzig",
	"Schwimmhalle Olvenstedt Magdeburg",
	"Schwimmhalle Süd Leipzig",
	"Schwimmhalle Südost Leipzig",
	"Schwimmhalle West Leipzig",
	"Schwimmsportkomplex Freiberger Platz Dresden",
	"Schwimmzentrum Kettwig Essen",
	"Schwimmzentrum Rüttenscheid Essen",
	"Seaside Beach Baldeney Essen",
	"See- und Hallenbad Stadt Senden",
	"Seerosenbad Kirchberg",
	"Seilerseebad Iserlohn",
	"Senner Waldbad Bielefeld",
	"SimmBad Simmerath",
	"Simmeringer Bad Wien",
	"Sommerbad Fürth",
	"Sommerbad Kleinzschocher Leipzig",
	"Sommerbad Schönefeld Leipzig",
	"Sommerbad Südost Leipzig",
	"Sonnen-Therme Eging am See",
	"Sonnenbad Karlsruhe",
	"Spickelbad Augsburg",
	"Sportbad An der Elster Leipzig",
	"Sportbad am Rabet Leipzig",
	"Sportbad Aquawede Bielefeld",
	"Sportbad Ingolstadt",
	"Sportbad Sennestedt Bielefeld",
	"Sportbad Thurmfeld Essen",
	"Spreebad Bautzen",
	"Stadionbad Köln",
	"Stadtbad Borbeck Essen",
	"Stadtbad Friedberg",
	"Stadtbad Halle",
	"Stadtbad Hohnstein",
	"Stadtbad Kupferdreh Essen",
	"Stadtbad Rheydt Mönchengladbach",
	"Stadtbad Salzgitter-Lebenstedt",
	"Stadtbad Sammys Dormagen",
	"Stadtbad Viersen (Schwimmen)",
	"Stadtbad Vilsbiburg",
	"Stadtbad Werden Essen",
	"Stadionbad Nürnberg",
	"Städtisches Hallenbad Bernburg",
	"Städtisches Schwimmbad Alsleben",
	"Stauseebad Cossebaude Dresden",
	"Stenkhoffbad Bottrop",
	"Strandbad Alte Donau Wien",
	"Strandbad Angelibad Wien",
	"Strandbad Gänsehäufel Wien",
	"Strandbad Klagenfurt",
	"Strandbad Knesebeck (Naturbad)",
	"Strandbad Lochen am See",
	"Strandbad Loretto Klagenfurt",
	"Strandbad Lörick (Freibad) Düsseldorf",
	"Strandbad Maiernigg Klagenfurt",
	"Strandbad Wostra Dresden",
	"Stukitzbad Graz",
	"Südbad Dortmund",
	"Südbad Münster",
	"Südbad - Hallen- und Freibad Recklinghausen",
	"TaunaBad Frei- und Hallenbad Oberursel",
	"Textorbad Frankfurt am Main",
	"Theresienbad Wien",
	"Thermalstrandbad Baden",
	"Therme Vierordtbad Karlsruhe",
	"TITUS THERMEN FITNESS CENTER",
	"Tübinger Freibad Tübingen",
	"Turmbergbad Karlsruhe",
	"Uhlandbad Tübingen",
	"Union Hallenbad Graz",
	"Vitusbad Mönchengladbach",
	"Volksbad Mönchengladbach",
	"Wahnbad Köln",
	"Waldbad Bienenbüttel",
	"Waldbad Bomlitz Walsrode",
	"Waldbad Hankensbüttel",
	"Waldbad Langebrück Dresden",
	"Waldbad Laxenburg",
	"Waldfreibad Heidenheim",
	"Waldfreibad Hiddenhausen",
	"Waldschwimmbad Kronberg",
	"Waldschwimmbad Rothenburg",
	"Warmfreibad Farchant",
	"Weiherhofbad Durlach Karlsruhe",
	"Welldorado Wels",
	"Wellnessoase Hummelhof Linz",
	"Werburger Waldbad Spenge",
	"Westbad Nürnberg",
	"Westbad Ulm",
	"Wiesenbad Bielefeld",
	"Zollstockbad Köln",
	"Zündorfbad Köln",
}

// KnownAliases maps common OCR/extracted location strings to the exact Typeform pool label.
var KnownAliases = map[string]string{
	"schwimm in bilk":                   "Schwimm' in Bilk Düsseldorf",
	"schwimm in bilk dusseldorf":        "Schwimm' in Bilk Düsseldorf",
	"schwimm in bilk düsseldorf":        "Schwimm' in Bilk Düsseldorf",
	"bädergesellschaft düsseldorf bilk": "Schwimm' in Bilk Düsseldorf",
	"munster therme":                    "Münster Therme Düsseldorf",
	"münster therme":                    "Münster Therme Düsseldorf",
	"münster-therme":                    "Münster Therme Düsseldorf",
	"dusselstrand":                      "Freizeitbad Düsselstrand Düsseldorf",
	"düsselstrand":                      "Freizeitbad Düsselstrand Düsseldorf",
	"allwetterbad flingern":             "Allwetterbad Flingern (Hallenbad) Düsseldorf",
	"rheinbad":                          "Hallen- und Freibad Rheinbad Düsseldorf",
	"badehaus benrath":                  "Badehaus Benrath Düsseldorf",
	"unterrath":                         "Gartenhallenbad Unterrath Düsseldorf",
	"niederheid":                        "Familienbad Niederheid Düsseldorf",
}
